import numpy as np
import matplotlib.pyplot as plt

fijas1_2500 = np.loadtxt("fijas_caso1_2500.txt")
fijas1_0 = np.loadtxt("fijas_caso1_0.txt")
fijas1_100 = np.loadtxt("fijas_caso1_100.txt")
fijas2_2500 = np.loadtxt("fijas_caso2_2500.txt")
fijas2_0 = np.loadtxt("fijas_caso2_0.txt")
fijas2_100 = np.loadtxt("fijas_caso2_100.txt")
abiertas1_2500 = np.loadtxt("abiertas_caso1_2500.txt")
abiertas1_0 = np.loadtxt("abiertas_caso1_0.txt")
abiertas1_100 = np.loadtxt("abiertas_caso1_100.txt")
abiertas2_2500 = np.loadtxt("abiertas_caso2_2500.txt")
abiertas2_0 = np.loadtxt("abiertas_caso2_0.txt")
abiertas2_100 = np.loadtxt("abiertas_caso2_100.txt")
periodicas1_2500 = np.loadtxt("periodicas_caso1_2500.txt")
periodicas1_0 = np.loadtxt("periodicas_caso1_0.txt")
periodicas1_100 = np.loadtxt("periodicas_caso1_100.txt")
periodicas2_2500 = np.loadtxt("periodicas_caso2_2500.txt")
periodicas2_0 = np.loadtxt("periodicas_caso2_0.txt")
periodicas2_100 = np.loadtxt("periodicas_caso2_100.txt")

t_fijas1_0 = np.zeros((100,100), dtype=float)
t_fijas1_100 = np.zeros((100,100), dtype=float)
t_fijas1_2500 = np.zeros((100,100), dtype=float)
t_fijas2_0 = np.zeros((100,100), dtype=float)
t_fijas2_100 = np.zeros((100,100), dtype=float)
t_fijas2_2500 = np.zeros((100,100), dtype=float)
t_abiertas1_0 = np.zeros((100,100), dtype=float)
t_abiertas1_100 = np.zeros((100,100), dtype=float)
t_abiertas1_2500 = np.zeros((100,100), dtype=float)
t_abiertas2_0 = np.zeros((100,100), dtype=float)
t_abiertas2_100 = np.zeros((100,100), dtype=float)
t_abiertas2_2500 = np.zeros((100,100), dtype=float)
t_periodicas1_0 = np.zeros((100,100), dtype=float)
t_periodicas1_100 = np.zeros((100,100), dtype=float)
t_periodicas1_2500 = np.zeros((100,100), dtype=float)
t_periodicas2_0 = np.zeros((100,100), dtype=float)
t_periodicas2_100 = np.zeros((100,100), dtype=float)
t_periodicas2_2500 = np.zeros((100,100), dtype=float)

def linealizar(matriz, data):
	k=0
	for i in range(100):
		for j in range(100):
			matriz[j][i]= data[k]
			k+=1

linealizar(t_fijas1_0, fijas1_0)
linealizar(t_fijas1_2500, fijas1_2500)
linealizar(t_fijas1_100, fijas1_100)
linealizar(t_fijas2_0, fijas2_0)
linealizar(t_fijas2_2500, fijas2_2500)
linealizar(t_fijas2_100, fijas2_100)
linealizar(t_abiertas1_0, abiertas1_0)
linealizar(t_abiertas1_2500, abiertas1_2500)
linealizar(t_abiertas1_100, abiertas1_100)
linealizar(t_abiertas2_0, abiertas2_0)
linealizar(t_abiertas2_2500, abiertas2_2500)
linealizar(t_abiertas2_100, abiertas2_100)
linealizar(t_periodicas1_0, periodicas1_0)
linealizar(t_periodicas1_2500, periodicas1_2500)
linealizar(t_periodicas1_100, periodicas1_100)
linealizar(t_periodicas2_0, periodicas2_0)
linealizar(t_periodicas2_2500, periodicas2_2500)
linealizar(t_periodicas2_100, periodicas2_100)

plt.imshow(t_fijas1_0)
plt.title(r"Temperatura en $^{\circ}$C de la placa en t=0s")
plt.xlabel(r"x (cm)")
plt.ylabel(r"y (cm)")
plt.colorbar()
plt.savefig("f1_0.pdf")
plt.close()

plt.imshow(t_fijas1_100)
plt.title("Temperatura en $^{\circ}$C de la placa en t=100s")
plt.xlabel(r"x (cm)")
plt.ylabel(r"y (cm)")
plt.colorbar()
plt.savefig("f1_100.pdf")
plt.close()

plt.imshow(t_fijas1_2500)
plt.title("Temperatura en $^{\circ}$C de la placa en t=2500s")
plt.xlabel(r"x (cm)")
plt.ylabel(r"y (cm)")
plt.colorbar()
plt.savefig("f1_2500.pdf")
plt.close()

plt.imshow(t_fijas2_0)
plt.title("Temperatura en $^{\circ}$C de la placa en t=0s")
plt.xlabel(r"x (cm)")
plt.ylabel(r"y (cm)")
plt.colorbar()
plt.savefig("f2_0.pdf")
plt.close()

plt.imshow(t_fijas2_100)
plt.title("Temperatura en $^{\circ}$C de la placa en t=100s")
plt.xlabel(r"x (cm)")
plt.ylabel(r"y (cm)")
plt.colorbar()
plt.savefig("f2_100.pdf")
plt.close()

plt.imshow(t_fijas2_2500)
plt.title("Temperatura en $^{\circ}$C de la placa en t=2500s")
plt.xlabel(r"x (cm)")
plt.ylabel(r"y (cm)")
plt.colorbar()
plt.savefig("f2_2500.pdf")
plt.close()

plt.imshow(t_abiertas1_0)
plt.title("Temperatura en $^{\circ}$C de la placa en t=0s")
plt.xlabel(r"x (cm)")
plt.ylabel(r"y (cm)")
plt.colorbar()
plt.savefig("a1_0.pdf")
plt.close()

plt.imshow(t_abiertas1_100)
plt.title("Temperatura en $^{\circ}$C de la placa en t=100s")
plt.xlabel(r"x (cm)")
plt.ylabel(r"y (cm)")
plt.colorbar()
plt.savefig("a1_100.pdf")
plt.close()

plt.imshow(t_abiertas1_2500)
plt.title("Temperatura en $^{\circ}$C de la placa en t=2500s")
plt.xlabel(r"x (cm)")
plt.ylabel(r"y (cm)")
plt.colorbar()
plt.savefig("a1_2500.pdf")
plt.close()

plt.imshow(t_abiertas2_0)
plt.title("Temperatura en $^{\circ}$C de la placa en t=0s")
plt.xlabel(r"x (cm)")
plt.ylabel(r"y (cm)")
plt.colorbar()
plt.savefig("a2_0.pdf")
plt.close()

plt.imshow(t_abiertas2_100)
plt.title("Temperatura en $^{\circ}$C de la placa en t=100s")
plt.xlabel(r"x (cm)")
plt.ylabel(r"y (cm)")
plt.colorbar()
plt.savefig("a2_100.pdf")
plt.close()

plt.imshow(t_abiertas2_2500)
plt.title("Temperatura en $^{\circ}$C de la placa en t=2500s")
plt.xlabel(r"x (cm)")
plt.ylabel(r"y (cm)")
plt.colorbar()
plt.savefig("a2_2500.pdf")
plt.close()

plt.imshow(t_periodicas1_0)
plt.title("Temperatura en $^{\circ}$C de la placa en t=0s")
plt.xlabel(r"x (cm)")
plt.ylabel(r"y (cm)")
plt.colorbar()
plt.savefig("p1_0.pdf")
plt.close()

plt.imshow(t_periodicas1_100)
plt.title("Temperatura en $^{\circ}$C de la placa en t=100s")
plt.xlabel(r"x (cm)")
plt.ylabel(r"y (cm)")
plt.colorbar()
plt.savefig("p1_100.pdf")
plt.close()

plt.imshow(t_periodicas1_2500)
plt.title("Temperatura en $^{\circ}$C de la placa en t=2500s")
plt.xlabel(r"x (cm)")
plt.ylabel(r"y (cm)")
plt.colorbar()
plt.savefig("p1_2500.pdf")
plt.close()

plt.imshow(t_periodicas2_0)
plt.title("Temperatura en $^{\circ}$C de la placa en t=0s")
plt.xlabel(r"x (cm)")
plt.ylabel(r"y (cm)")
plt.colorbar()
plt.savefig("p2_0.pdf")
plt.close()

plt.imshow(t_periodicas2_100)
plt.title("Temperatura en $^{\circ}$C de la placa en t=100s")
plt.xlabel(r"x (cm)")
plt.ylabel(r"y (cm)")
plt.colorbar()
plt.savefig("p2_100.pdf")
plt.close()

plt.imshow(t_periodicas2_2500)
plt.title("Temperatura en $^{\circ}$C de la placa en t=2500s")
plt.xlabel(r"x (cm)")
plt.ylabel(r"y (cm)")
plt.colorbar()
plt.savefig("p2_2500.pdf")
plt.close()

#GRAFICAS DE PROMEDIOS
fijas1_prom = np.loadtxt("fijas_caso1_prom.txt")
fijas2_prom = np.loadtxt("fijas_caso2_prom.txt")
abiertas1_prom = np.loadtxt("abiertas_caso1_prom.txt")
abiertas2_prom = np.loadtxt("abiertas_caso2_prom.txt")
periodicas1_prom = np.loadtxt("periodicas_caso1_prom.txt")
periodicas2_prom = np.loadtxt("periodicas_caso2_prom.txt")

tiempo = fijas1_prom[:,0]
f1_mean = fijas1_prom[:,1]
f2_mean = fijas2_prom[:,1]
a1_mean = abiertas1_prom[:,1]
a2_mean = abiertas2_prom[:,1]
p1_mean = periodicas1_prom[:,1]
p2_mean = periodicas2_prom[:,1]

plt.figure()
plt.plot(tiempo, f1_mean, label=r"$Fijas$")
plt.plot(tiempo, a1_mean, label=r"$Abiertas$")
plt.plot(tiempo, p1_mean, label=r"$Peri\'odicas$")
plt.title("Promedio de temperaturas para el caso 1")
plt.xlabel("Tiempo (s)")
plt.ylabel("Temperatura $^{\circ}$C")
plt.legend()
plt.savefig("prom1.pdf")
plt.close()

plt.figure()
plt.plot(tiempo, f2_mean, label=r"$Fijas$")
plt.plot(tiempo, a2_mean, label=r"$Abiertas$")
plt.plot(tiempo, p2_mean, label=r"$Peri\'odicas$")
plt.title("Promedio de temperaturas para el caso 2")
plt.xlabel("Tiempo (s)")
plt.ylabel("Temperatura $^{\circ}$C")
plt.legend()
plt.savefig("prom2.pdf")
plt.close()
